import { useState } from 'react'
import { X, FileText, Shield } from 'lucide-react'

export default function LegalPage({ onClose }) {
  const [activeTab, setActiveTab] = useState('terms')

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[85vh] flex flex-col">

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100">
          <div className="flex gap-1 bg-slate-100 rounded-xl p-1">
            <button
              onClick={() => setActiveTab('terms')}
              className={`flex items-center gap-2 px-4 py-1.5 rounded-lg text-[12px] font-semibold transition-all ${
                activeTab === 'terms'
                  ? 'bg-white text-slate-800 shadow-sm'
                  : 'text-slate-500 hover:text-slate-700'
              }`}
            >
              <FileText size={13}/> Terms of Service
            </button>
            <button
              onClick={() => setActiveTab('privacy')}
              className={`flex items-center gap-2 px-4 py-1.5 rounded-lg text-[12px] font-semibold transition-all ${
                activeTab === 'privacy'
                  ? 'bg-white text-slate-800 shadow-sm'
                  : 'text-slate-500 hover:text-slate-700'
              }`}
            >
              <Shield size={13}/> Privacy Policy
            </button>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors"
          >
            <X size={16}/>
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-6 py-5 text-[13px] text-slate-700 space-y-4 leading-relaxed">
          {activeTab === 'terms' && (
            <>
              <p className="text-[11px] text-slate-400 font-medium uppercase tracking-wider">Last updated: January 2025</p>
              <h3 className="text-[15px] font-bold text-slate-900">Terms of Service</h3>

              <section className="space-y-2">
                <h4 className="font-semibold text-slate-800">1. Acceptance of Terms</h4>
                <p>By accessing or using Axiom Intelligence ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
              </section>

              <section className="space-y-2">
                <h4 className="font-semibold text-slate-800">2. Description of Service</h4>
                <p>Axiom Intelligence is a business intelligence platform that enables organisations to upload financial and operational data, track KPIs, generate insights, and receive AI-assisted analysis. The Service is intended for business use only.</p>
              </section>

              <section className="space-y-2">
                <h4 className="font-semibold text-slate-800">3. Eligibility</h4>
                <p>The Service is available to organisations using work email addresses. Access using personal or free email providers (such as Gmail, Yahoo, Hotmail, etc.) is not permitted. By registering, you represent that you are authorised to bind your organisation to these terms.</p>
              </section>

              <section className="space-y-2">
                <h4 className="font-semibold text-slate-800">4. Your Data</h4>
                <p>You retain all ownership rights to the data you upload. You grant us a limited licence to process your data solely to provide the Service. We do not share your data with third parties except as necessary to operate the Service (e.g. hosting providers) or as required by law.</p>
              </section>

              <section className="space-y-2">
                <h4 className="font-semibold text-slate-800">5. Acceptable Use</h4>
                <p>You agree not to misuse the Service, including attempting to gain unauthorised access to other users' data, uploading malicious content, or using the Service in any manner that violates applicable law.</p>
              </section>

              <section className="space-y-2">
                <h4 className="font-semibold text-slate-800">6. AI-Generated Content</h4>
                <p>Insights and analysis generated by the AI assistant ("Anika") are provided for informational purposes only and do not constitute financial, investment, or professional advice. You are responsible for independently verifying any outputs before making business decisions.</p>
              </section>

              <section className="space-y-2">
                <h4 className="font-semibold text-slate-800">7. Limitation of Liability</h4>
                <p>To the maximum extent permitted by law, Axiom Intelligence and its operators shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service. The Service is provided "as is" without warranties of any kind.</p>
              </section>

              <section className="space-y-2">
                <h4 className="font-semibold text-slate-800">8. Changes to Terms</h4>
                <p>We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the revised Terms.</p>
              </section>

              <section className="space-y-2">
                <h4 className="font-semibold text-slate-800">9. Contact</h4>
                <p>For questions about these Terms, contact us at support@axiomsync.ai.</p>
              </section>
            </>
          )}

          {activeTab === 'privacy' && (
            <>
              <p className="text-[11px] text-slate-400 font-medium uppercase tracking-wider">Last updated: January 2025</p>
              <h3 className="text-[15px] font-bold text-slate-900">Privacy Policy</h3>

              <section className="space-y-2">
                <h4 className="font-semibold text-slate-800">1. Information We Collect</h4>
                <p>We collect the following information to provide the Service:</p>
                <ul className="list-disc list-inside space-y-1 text-slate-600 pl-2">
                  <li>Work email address used to authenticate your account</li>
                  <li>Business data you upload (financial metrics, KPIs, operational data)</li>
                  <li>Usage data (which features you use, login timestamps)</li>
                  <li>Company settings and preferences you configure</li>
                </ul>
              </section>

              <section className="space-y-2">
                <h4 className="font-semibold text-slate-800">2. How We Use Your Information</h4>
                <p>Your information is used to:</p>
                <ul className="list-disc list-inside space-y-1 text-slate-600 pl-2">
                  <li>Provide, operate, and improve the Service</li>
                  <li>Generate AI-powered insights from your data</li>
                  <li>Send authentication links to your email</li>
                  <li>Monitor platform health and security</li>
                </ul>
              </section>

              <section className="space-y-2">
                <h4 className="font-semibold text-slate-800">3. Data Isolation</h4>
                <p>Each organisation's data is stored in a separate workspace and is never accessible to other users. All queries to the database are scoped to your workspace ID, enforced at the server level.</p>
              </section>

              <section className="space-y-2">
                <h4 className="font-semibold text-slate-800">4. Data Retention</h4>
                <p>Your data is retained for as long as your account is active. You may delete all your workspace data at any time from Company Settings. Upon account deletion, all associated data is permanently removed from our systems.</p>
              </section>

              <section className="space-y-2">
                <h4 className="font-semibold text-slate-800">5. Third-Party Services</h4>
                <p>We use the following third-party services to operate the platform:</p>
                <ul className="list-disc list-inside space-y-1 text-slate-600 pl-2">
                  <li>Render — cloud hosting and infrastructure</li>
                  <li>Anthropic Claude — AI analysis engine</li>
                  <li>Resend — transactional email delivery</li>
                </ul>
                <p>Each provider has their own privacy policy governing how they handle data passed to them.</p>
              </section>

              <section className="space-y-2">
                <h4 className="font-semibold text-slate-800">6. Security</h4>
                <p>We use industry-standard security measures including HTTPS encryption, JWT-based authentication, and server-side workspace isolation. We do not store passwords.</p>
              </section>

              <section className="space-y-2">
                <h4 className="font-semibold text-slate-800">7. Your Rights</h4>
                <p>You have the right to access, correct, or delete the personal data we hold about you. To exercise these rights, contact us at support@axiomsync.ai.</p>
              </section>

              <section className="space-y-2">
                <h4 className="font-semibold text-slate-800">8. Contact</h4>
                <p>For privacy-related enquiries, contact us at support@axiomsync.ai.</p>
              </section>
            </>
          )}
        </div>
      </div>
    </div>
  )
}
